---
- name: Create the uptime monitor script
  template:
    src: uptime_monitor.sh.j2
    dest: /usr/local/bin/uptime-monitor.sh
    mode: '0755'

- name: Ensure uptime monitor runs on startup
  lineinfile:
    path: "/entrypoint.sh"
    line: "/usr/local/bin/uptime-monitor.sh &"
    insertafter: ".*"
    state: present

