---
- name: Create the uptime monitor script
  template:
    src: uptime_monitor.sh.j2
    dest: /usr/local/bin/uptime-monitor.sh
    mode: '0755'

- name: Ensure uptime monitor script is executable
  file:
    path: /usr/local/bin/uptime-monitor.sh
    mode: '0755'
    state: file

- name: Start Uptime Kuma Monitor in Background
  shell: "nohup /usr/local/bin/uptime-monitor.sh >> /tmp/uptime-monitor.log 2>&1 &"
  args:
    executable: /bin/bash

