---
- name: Create the uptime monitor script
  template:
    src: uptime_monitor.sh.j2
    dest: /usr/local/bin/uptime-monitor.sh
    mode: '0755'

- name: Ensure uptime monitor service is enabled
  template:
    src: uptime_monitor.service.j2
    dest: /etc/systemd/system/uptime-monitor.service

- name: Reload systemd and start the uptime monitor
  systemd:
    name: uptime-monitor
    enabled: yes
    state: started
    daemon_reload: yes
