apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: open-source-template-
  labels:
    app: open-source-template
spec:
  selector:
    matchLabels:
      app: open-source-template
  template:
    metadata:
      labels:
        app: open-source-template
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
      containers:
        - name: ubuntu
          image: ubuntu:22.04
          hostNetwork: true
          command:
            - /bin/bash
          args:
            - -c
            - |
              ########################################
              ## 📝 Developer Configuration Section ##
              ########################################

              ### Modify these variables to easily adjust configuration settings when developing new deployments ###

              # Ansible Configuration
              ANSIBLE_PLAYBOOK="environment_template.yml"  # Name of the Ansible playbook (edit per deployment!)
              ANSIBLE_PLAYBOOK_PATH="/mnt/data/FluxEdge-Deployment-Toolbox/ansible/playbooks/$ANSIBLE_PLAYBOOK"  # Full path (auto-generated)
              ANSIBLE_CONFIG_PATH="/mnt/data/FluxEdge-Deployment-Toolbox/ansible/ansible.cfg"

              # Jupyter Configuration
              JUPYTER_DEPLOY="true"   # set this to true if you want to add jupyter to the deployment (UI can override option!)
              JUPYTER_TOKEN="jupyter_test_token"   # in the future the UI will manage or inject this value automagically
              JUPYTER_ANSIBLE_PLAYBOOK="environment_jupyter.yml"  # Name of the Ansible playbook (edit per deployment!)
              JUPYTER_ANSIBLE_PLAYBOOK_PATH="/mnt/data/FluxEdge-Deployment-Toolbox/ansible/playbooks/$JUPYTER_ANSIBLE_PLAYBOOK"  # Full path (auto-generated)
              JUPYTER_ANSIBLE_CONFIG_PATH="/mnt/data/FluxEdge-Deployment-Toolbox/ansible/ansible.cfg"

              

              # Watchdog Configuration
              WATCHDOG_TIMEOUT=120  # ⏳ Maximum time (seconds) before watchdog forcefully kills setup (edit per deployment!)
              SETUP_LOG="/tmp/setup.log"  # 📝 Log file for additional debugging
              
              # Readiness Probe Configuration (the below readiness probe settings do not currently work without ArgoCD implementation)
              READINESS_INITIAL_DELAY=5  # ⏳ Time before the first readiness check (seconds)
              READINESS_PERIOD=10  # 🔄 Interval between readiness checks (seconds)
              READINESS_FAILURE_THRESHOLD=6  # ❌ Max failed checks before marking as failed (edit this to change total wait time!!!)
              READINESS_SUCCESS_THRESHOLD=1  # ✅ Required successful check count to mark as ready

              ########################################
              ##### End Developer Configuration ######
              ########################################

              setup() {
                echo "Starting setup process with a watchdog timeout of $WATCHDOG_TIMEOUT seconds..."
                echo "Logs will be stored in $SETUP_LOG"

                # 🛑 Start a watchdog process to terminate stuck deployments
                (
                  sleep $WATCHDOG_TIMEOUT
                  echo "❌ ERROR: Setup process timed out after $WATCHDOG_TIMEOUT seconds." | tee /tmp/setup-failed
                  pkill -P $$  # Kill all child processes
                  exit 1
                ) &
                TIMEOUT_PID=$!  # Store the watchdog process ID
                
                # 🏗️ Begin setup tasks
                {

                  echo "Updating system and installing dependencies..." | tee -a $SETUP_LOG
                  export DEBIAN_FRONTEND=noninteractive
                  apt-get -y update && apt-get -y upgrade && apt-get -y install tzdata curl vim git ansible 2>&1 | tee -a $SETUP_LOG || {
                    echo "❌ ERROR: Failed to install dependencies." | tee -a /tmp/setup-failed
                    kill $TIMEOUT_PID
                    exit 1
                  }

                  # Check if the mount path exists
                  echo "Checking for external mount path..." | tee -a $SETUP_LOG
                  if [ ! -d "/mnt/data" ]; then
                      echo "❌ ERROR: Mount path /mnt/data does not exist. Deployment cannot continue." | tee -a /tmp/setup-failed
                      kill $TIMEOUT_PID
                      exit 1
                  fi

                  # Clone Open Source deployment repository
                  if [ ! -d "/mnt/data/FluxEdge-Deployment-Toolbox" ]; then
                      echo "Cloning FluxEdge-Deployment-Toolbox..." | tee -a $SETUP_LOG
                      git clone https://github.com/helloskyy-io/FluxEdge-Deployment-Toolbox /mnt/data/FluxEdge-Deployment-Toolbox 2>&1 | tee -a $SETUP_LOG
                  else
                      echo "Repository already exists in /mnt/data. Pulling latest changes..." | tee -a $SETUP_LOG
                      cd /mnt/data/FluxEdge-Deployment-Toolbox && git pull 2>&1 | tee -a $SETUP_LOG
                  fi

                  # ✅ Run Ansible Playbook with explicit config path
                  echo "Running Ansible Playbook: $ANSIBLE_PLAYBOOK_PATH with config: $ANSIBLE_CONFIG_PATH" | tee -a $SETUP_LOG
                  ANSIBLE_CONFIG="$ANSIBLE_CONFIG_PATH" ansible-playbook -i localhost, -c local "$ANSIBLE_PLAYBOOK_PATH" 2>&1 | tee -a $SETUP_LOG || {
                    echo "❌ ERROR: Ansible playbook execution failed." | tee -a /tmp/setup-failed
                    kill $TIMEOUT_PID
                    exit 1
                  }

                  # ✅ Run Ansible Jupyter Playbook with explicit config path only if Jupyter flag is set.
                  if [ "$JUPYTER_DEPLOY" = "true" ]; then
                    echo "Running Ansible Jupyter Playbook: $JUPYTER_ANSIBLE_PLAYBOOK_PATH with config: $JUPYTER_ANSIBLE_CONFIG_PATH" | tee -a $SETUP_LOG
                    ANSIBLE_CONFIG="$JUPYTER_ANSIBLE_CONFIG_PATH" ansible-playbook -i localhost, -c local "$JUPYTER_ANSIBLE_PLAYBOOK_PATH" -e "jupyter_token=$JUPYTER_TOKEN" 2>&1 | tee -a $SETUP_LOG || {
                      echo "❌ ERROR: Jupyter Ansible playbook execution failed." | tee -a /tmp/setup-failed
                      kill $TIMEOUT_PID
                      exit 1
                    }
                  else
                    echo "Skipping Jupyter installation as JUPYTER_DEPLOY is set to 'false'." | tee -a $SETUP_LOG
                  fi

                  

                  # ✅ If setup finishes successfully, kill watchdog and mark as ready
                  kill $TIMEOUT_PID
                  touch /tmp/setup-finished
                  echo "✅ Setup completed successfully in under $WATCHDOG_TIMEOUT seconds!" | tee -a $SETUP_LOG
                } &
                
                # 🚀 Wait for setup to complete
                wait $!
              }

              # Execute the setup function
              setup
              
              # Keep container alive
              tail -f /dev/null

          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  if [ -f /tmp/setup-failed ]; then
                    echo "Deployment failed."
                    exit 1
                  elif [ -f /tmp/setup-finished ]; then
                    exit 0
                  else
                    exit 1
                  fi
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
            successThreshold: 1
          ports:
            - containerPort: 80
            - containerPort: 8888
          resources:
            requests:
              cpu: 4000m
              memory: 8192M
              ephemeral-storage: 10G
            limits:
              cpu: 4000m
              memory: 8192M
              ephemeral-storage: 10G
          volumeMounts:
            - mountPath: /mnt/data
---
apiVersion: v1
kind: Service
metadata:
  name: open-source-template-service
  labels:
    app: open-source-template
spec:
  selector:
    app: open-source-template
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: jupyter
      protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
