---
- name: Debug Miniconda installation variables
  debug:
    msg: "Installing Miniconda at {{ conda_root }} and setting up environment {{ conda_env_name }}."
  when: ansible_verbosity >= 2

- name: Install required APT dependencies for Miniconda
  include_role:
    name: configure_apt_packages
  vars:
    configure_apt_packages_apt_packages:
      - wget
      - bzip2

- name: Check if Miniconda is already installed
  stat:
    path: "{{ conda_root }}/bin/conda"
  register: conda_installed

- name: Download Miniconda installer
  get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest: "/tmp/miniconda.sh"
    mode: '0755'
  when: not conda_installed.stat.exists

- name: Install Miniconda
  command: bash /tmp/miniconda.sh -b -p {{ conda_root }}
  register: conda_install
  changed_when: false
  failed_when: not dev_mode and conda_install.rc != 0  # Fails in production, logs in dev

- name: Ensure Conda is in the PATH
  lineinfile:
    path: "/etc/profile.d/conda.sh"
    line: "export PATH={{ conda_root }}/bin:$PATH"
    create: yes
    mode: '0644'

- name: Initialize Conda for Bash
  shell: "{{ conda_root }}/bin/conda init bash"

- name: Check if Conda environment exists
  command: "{{ conda_root }}/bin/conda env list"
  register: conda_envs
  changed_when: false

- name: Create Conda environment if not exists
  command: "{{ conda_root }}/bin/conda create -y -n {{ conda_env_name }} python={{ python_version }}"
  when: "conda_env_name not in conda_envs.stdout"
  register: conda_create_result
  failed_when: not dev_mode and conda_create_result.rc != 0  # Fail in production, continue in dev

- name: Install Python dependencies inside Conda environment
  command: "{{ conda_root }}/bin/conda run -n {{ conda_env_name }} -- conda install -y {{ conda_packages | join(' ') }}"
  register: conda_install_result
  failed_when: not dev_mode and conda_install_result.rc != 0  # Fail in production, continue in dev

- name: Debug Conda installation results
  debug:
    var: conda_install_result
  when: ansible_verbosity >= 2

# ✅ Auto-activate Conda for interactive user sessions
- name: Ensure Conda environment activates for user sessions
  lineinfile:
    path: "/root/.bashrc"
    line: "source {{ conda_root }}/bin/activate {{ conda_env_name }}"
    create: yes
    mode: '0644'

